### PR TITLE
 Immediate stargate dialling using DHD

### PR DESCRIPTION
**Pull request by Radviger**
Totally forgot about this feature for about a couple of weeks

### CODE REVIEW

**Comment by Dockter** [comment]
Radviger, how exactly does this work?

**Comment by Radviger** [comment]
When you press a button on a DHD, a chervron gets locked on the stargate without a ring rotation. But if you use a computer to dial an address, the ring will rotate. 
P.S. Sorry for such a long response

**Comment by Dockter** [comment]
This is going to be a tricky feature.  I'd like to add both versions with differing DHD's

**Comment by Radviger** [comment]
There is a config option I've added to disable it. I agree that this is a kind of a tricky feature but adding a new type of DHD sounds a little bit weird to me. Maybe some kind of an upgrade will be better?

**Comment by TherayTharow** [comment]
I agree with a upgrade instead of new DHD  something like shift clinking on DHD with upgrade 
then in the fuel gui have it say that this DHD is upgrade
or ,hold ctrl when press big button is center to fast dial

**Comment by Dockter** [comment]
OK, I've had a chance to play with this. Give me a little bit to try and figure out how you implemented it and how it affects the main TE

**Comment by Dockter** [comment]
One issue,  when I dial, regardless of what I dial, I dont seem to get this sound: https://github.com/AlmuraDev/SGCraft/blob/99f130c3a42a11fdc8eb4fecfe33ecff5c88d7e0/src/resources/assets/sgcraft/sounds/gate_open_long.ogg

What am I missing?

**Comment by Dockter** [comment]
Ok, figured out that the sound isn't specified.  I changed it out for the normal gate_open sound but it seems to play about 500 ms too late.

**Comment by TherayTharow** [comment]
Getting to work i see. Also my notifications sux bad, i need to go fix that so i can see when people say things

**Comment by Radviger** [comment]
It's just an unused sound that I forgot to delete : )

**Comment by Dockter** [comment]
Please dont delete it, it has a purpose.

**Comment by Radviger** [comment]
What purpose?

**Comment by Dockter** [comment]
I decided to pull this PR as is.  I've already slightly modified it to put the control of the immediate dial on the DHDTE instead of the SGBaseTE.  This will allow for more flexibility

**Pull request merged**
