### PR TITLE
Added Support for Simplified Chinese language

### PR DESCRIPTION
**Pull request by f0rb1d**

### CODE REVIEW

**Comment by TherayTharow** [comment]
👍

**Comment by liach** [comment]
眼瞎了，这个pr活了这么久我居然从来没看到

**Comment by TherayTharow** [comment]
"I’ve been blind, this pr has lived for so long, I never saw it." -liach 2019

**Comment by f0rb1d** [comment]
What the hell has just happened

**Comment by TherayTharow** [comment]
i gave a thumbs up then liach commented in Simplified Chinese then i turned it back in to english

**Comment by f0rb1d** [comment]
Yea I can clearly see that. But why is this pr still open.

**Comment by TherayTharow** [comment]
because we don't have write perms

**Comment by f0rb1d** [comment]
I know, but why the contributors didn't see it :?

**Comment by TherayTharow** [comment]
@Dockter has write perms; i have no idea why they didn't see it

**Comment by TherayTharow** [comment]
i watch this repo and i didn't see it

**Pull request merged**
