### PR TITLE
Added Scala transformer exclusion

### PR DESCRIPTION
**Pull request by Foxxtail1**
Fixed the error: java.lang.ClassCircularityError: scala/Predef$

This fixes the issue AlmuraDev/SGCraft#117

### CODE REVIEW

**Comment by Dockter** [comment]
This makes SGCraft a coremod doesn't it?

**Comment by Foxxtail1** [comment]
I guess it does. If that's an issue a separate coremod would have to be made to apply that fix on regular Forge. Might be better to do that since SGCraft isn't the only mod that uses Mixin.

**Comment by Foxxtail1** [comment]
I've done a separate mod that applies that fix. [ForgeMixinFix](https://github.com/Foxxtail1/ForgeMixinFix) I don't see the point in adding a functionality that could be required by many other mods.

**Comment by Foxxtail1** [comment]
https://www.curseforge.com/minecraft/mc-mods/forge-mixin-fix

**Pull request closed without merging**
