### PR TITLE
Improvements to Stargate world generation

### PR DESCRIPTION
**Pull request by dallenwilson**
Various changes and improvements to the world generation of stargates.

Original pull request, changes I made just to get things to compile and run without actually modifying code yet:
- Bumped forge version and MCP snapshot to latest versions
- Updated urls for new COFH deps added in last commit, fixes auto-download
error as described in issue #134 

The following was done without realizing it would be automatically added to the existing pull request:
- Re-did Stargate generation code for Desert Temples, Jungle Temples, Igloos and Swamp Huts
- Added Stargate generation for Villages, Ocean Monuments and Nether Fortresses
- Tweaked Tok'Ra villager spawning in villages to remove the need for Mixins.

### CODE REVIEW

**Comment by dallenwilson** [comment]
Edited PR title and initial comment, as I did not realize all the commits to the master branch on my end were getting added to this PR automagically. Lesson learned I suppose.

**Comment by Dockter** [comment]
I look forward to testing this....

**Comment by dallenwilson** [comment]
Let me know what you find, bug-wise. I've never worked with Java before, or tried my hand at minecraft modding. Bound to be something I missed. Lots of detail gets echo'd to the console if debugStructures is true, and most of my testing was done with the seed 'BOOKZED' and a large list of journeymap waypoints.

I did find a single case of an incomplete generation on a jungle temple, but I chalked that up to the same sort of weird half-done generation encountered in vanilla sometimes, and stopped worrying about it. It was utterly unreproducible outside that specific temple.

**Comment by Dockter** [comment]
Found one issue thus far that has prevented me from testing this.  

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Thermal Foundation (thermalfoundation)
Caused by: java.lang.NoSuchMethodError: net.minecraft.block.Block.setUnlocalizedName(Ljava/lang/String;)Lnet/minecraft/block/Block;

Did you push the MCP version too far ahead?

**Comment by Dockter** [comment]
Likely because you changed some of the dependencies to deob versions, which is likely giving me my indev run in-ide mode.

**Comment by Dockter** [comment]
Also, can't push the mcp/forge build ahead of SpongeForge or you break compatibility with it, which is important.

**Comment by dallenwilson** [comment]
Gradle deps were changed to deobf versions because gradlew build wouldn't compile at all as it was, ran in to exactly the problems as described in #134 and the deobf versions seemed to fix things. I did bump the MCP and forge versions to the latest available, I wasn't aware SpongeForge was tied in to them. I can cheerfully revert it back.

**Comment by dallenwilson** [comment]
I managed to get gradlew to successfully build a fresh clone of your repo without touching anything in gradle.properties. BUILDING.txt was missing a step, and I had to downgrade my version of openjdk from 8.242 to 8.232. I'll close this for now and try again later.

**Comment by Dockter** [comment]
I'm re-reviewing this code; I like the main commit you did to change generation.

**Pull request merged**
