### PR TITLE
Small new features again

### PR DESCRIPTION
**Pull request by Radviger**
Gate* ring animation... (typo)

### CODE REVIEW

**Comment by Dockter** [comment]
@Radviger this PR introduced an issue I didn't catch until after I merged it.  Even if the IRIS on the destination gate is open it still thinks its closed.

**Comment by Radviger** [comment]
Fixed in my branch. I'll send it as another PR.

**Comment by Dockter** [comment]
I had already found and fixed this prior to your PR.  Question:  what was the reasoning behind slowing down the dialing sequence?

**Comment by Radviger** [comment]
The reasoning is that previously gate rotation speed was different for different angles betweeen two chevrons and that was really annoying. Now the rotation looks more realistic and similar to the original SG series.
P.S. Actually there is a static field in SGBaseTE called 'ringRotationSpeed' so you can increase the rotation speed by increasing it's value.

**Comment by Radviger** [comment]
Also the ring is now able to rotate both left and right correctly.

**Comment by Dockter** [comment]
What are your thought of creating a way that makes the DHD dial without spinning the ring.  Following the stargate methodology, the gate is suppose to lock each chevron without physically moving to do so.

**Comment by Radviger** [comment]
I've already thought about that just a few hours ago and now I'm digging into it,

**Pull request merged**
